language: ruby
sudo: required
rvm: 2.2.2

cache:
  - bundler

script:
  - bundle install
  - bundle exec rspec

notifications:
  slack:
    rooms: creative-group-team:HbG6Us2kmwJUpSchT64NmZ9G
    on_success: always
